### PR TITLE
Added .json extension to lang file

### PR DESCRIPTION
**Pull request by cph101**
No clue how I missed that the first time 🤦‍♂️

### CODE REVIEW

**Comment by MoriyaShiine** [comment]
There's a few new entries, please add them and I'll merge before release

**Comment by MoriyaShiine** [comment]
More entries, removed some. If I happen to add back the ones I removed I can grab them from your older commits

**Comment by cph101** [comment]
Alright, will do

**Comment by MoriyaShiine** [comment]
Okay lang entries are finalized this update, you can commit

**Pull request merged**
